openapi-processor-mapping: v17

options:
  package-name: uk.co.dajohnston
  model-name-suffix: Dto
  javadoc: true
  format-code: false
  bean-validation: jakarta
  model-type: record
map:
  result: org.springframework.http.ResponseEntity
  types:
    - type: string:uuid => java.util.UUID
    - type: array => java.util.List
    - type: object @ lombok.Builder
  paths:
    /api/users/me:
      parameters:
        - add: jwt => org.springframework.security.oauth2.jwt.JwtClaimAccessor
    /api/households:
      parameters:
        - add: jwt => org.springframework.security.oauth2.jwt.JwtClaimAccessor
    /api/households/{householdId}/join:
      parameters:
        - add: jwt => org.springframework.security.oauth2.jwt.JwtClaimAccessor
    /api/households/{householdId}/invitations:
      parameters:
        - add: jwt => org.springframework.security.oauth2.jwt.JwtClaimAccessor
