name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened ]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 26
        uses: actions/setup-java@v5
        with:
          java-version: '26'
          distribution: 'corretto'
          cache: gradle
      - name: Cache SonarCloud packages
        uses: actions/cache@v5
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Grant execute permission for gradlew
        run: chmod +x backend/gradlew
      - name: Build and Test Backend
        env:
          TEST_AUTH0_CLIENT_ID: ${{ secrets.TEST_AUTH0_CLIENT_ID }}
          TEST_AUTH0_CLIENT_SECRET: ${{ secrets.TEST_AUTH0_CLIENT_SECRET }}
          TEST_AUTH0_AUDIENCE: ${{ secrets.TEST_AUTH0_AUDIENCE }}
          TEST_AUTH0_TOKEN_URL: ${{ secrets.TEST_AUTH0_TOKEN_URL }}
          TEST_AUTH0_USERNAME: ${{ secrets.TEST_AUTH0_USERNAME }}
          TEST_AUTH0_PASSWORD: ${{ secrets.TEST_AUTH0_PASSWORD }}
          AUTH0_MANAGEMENT_CLIENT_ID: ${{ secrets.AUTH0_MANAGEMENT_CLIENT_ID }}
          AUTH0_MANAGEMENT_CLIENT_SECRET: ${{ secrets.AUTH0_MANAGEMENT_CLIENT_SECRET }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        working-directory: backend
        run: ./gradlew build spotlessCheck sonar --info
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v6
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/**/TEST-*.xml'

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install dependencies
        working-directory: frontend
        run: npm ci
      - name: Run Frontend Lint and Test
        working-directory: frontend
        run: |
          npm run lint
          npm test
      - name: Build Frontend
        working-directory: frontend
        run: npm run build
      - name: Lighthouse CI
        working-directory: frontend
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
        run: |
          npm install -g @lhci/cli@0.15.1
          lhci autorun
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        with:
          projectBaseDir: 'frontend'
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
