name: PR Integration Tests
on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened ]
env:
  GCP_REGION: europe-west1
  GCP_REPOSITORY: portal-artifacts
  IMAGE_NAME: portal-backend
jobs:
  integration-tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up JDK 26
        uses: actions/setup-java@v5
        with:
          java-version: '26'
          distribution: 'corretto'
          cache: gradle

      - name: Run Backend Integration Tests
        working-directory: backend
        env:
          TEST_AUTH0_CLIENT_ID: ${{ secrets.TEST_AUTH0_CLIENT_ID }}
          TEST_AUTH0_CLIENT_SECRET: ${{ secrets.TEST_AUTH0_CLIENT_SECRET }}
          TEST_AUTH0_AUDIENCE: ${{ secrets.TEST_AUTH0_AUDIENCE }}
          TEST_AUTH0_TOKEN_URL: ${{ secrets.TEST_AUTH0_TOKEN_URL }}
        run: |
          ./gradlew integrationTest

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Install Playwright Browsers
        working-directory: frontend
        run: npx playwright install --with-deps chromium

      - name: Run Frontend E2E Tests
        working-directory: frontend
        env:
          BASE_URL: ${{ secrets.VERCEL_PREVIEW_URL }} # Ideally would get this from Vercel
        run: npm run test:e2e
